<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

namespace Apikeyserver;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * response for RequestKillKey and RequestPermKillKey
 *
 * Generated from protobuf message <code>apikeyserver.GenericKillResponse</code>
 */
class GenericKillResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool result = 1;</code>
     */
    protected $result = false;
    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 2;</code>
     */
    protected $time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $result
     *     @type int|string $time
     *           unixNano
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ApiKeyServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool result = 1;</code>
     * @return bool
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>bool result = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkBool($var);
        $this->result = $var;

        return $this;
    }

    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 2;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

