<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

namespace Apikeyserver;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * responding to RequestKey
 *
 * Generated from protobuf message <code>apikeyserver.GetKeyResponse</code>
 */
class GetKeyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string type = 3;</code>
     */
    protected $type = '';
    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
     */
    private $items;
    /**
     * no keys remaining
     *
     * Generated from protobuf field <code>bool exhausted = 6;</code>
     */
    protected $exhausted = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $name
     *     @type string $type
     *     @type int|string $time
     *           unixNano
     *     @type \Apikeyserver\KeyResponseRemaining[]|\Google\Protobuf\Internal\RepeatedField $items
     *     @type bool $exhausted
     *           no keys remaining
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ApiKeyServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
     * @param \Apikeyserver\KeyResponseRemaining[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Apikeyserver\KeyResponseRemaining::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * no keys remaining
     *
     * Generated from protobuf field <code>bool exhausted = 6;</code>
     * @return bool
     */
    public function getExhausted()
    {
        return $this->exhausted;
    }

    /**
     * no keys remaining
     *
     * Generated from protobuf field <code>bool exhausted = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setExhausted($var)
    {
        GPBUtil::checkBool($var);
        $this->exhausted = $var;

        return $this;
    }

}

