<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

namespace Apikeyserver;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * response for RequestServerInfo
 *
 * Generated from protobuf message <code>apikeyserver.GetServerInfoResponse</code>
 */
class GetServerInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * keys.ServerVersion
     *
     * Generated from protobuf field <code>string serverVersion = 1;</code>
     */
    protected $serverVersion = '';
    /**
     * keys.TotalExhaustions
     *
     * Generated from protobuf field <code>uint32 keyExhaustions = 2;</code>
     */
    protected $keyExhaustions = 0;
    /**
     * keys.TotalPerMinute
     *
     * Generated from protobuf field <code>uint64 totalAvailableUsesPerMin = 3;</code>
     */
    protected $totalAvailableUsesPerMin = 0;
    /**
     * keys.TotalKeysServed
     *
     * Generated from protobuf field <code>uint64 totalKeysServed = 4;</code>
     */
    protected $totalKeysServed = 0;
    /**
     * computed
     *
     * Generated from protobuf field <code>uint64 totalKeysKilled = 5;</code>
     */
    protected $totalKeysKilled = 0;
    /**
     * Generated from protobuf field <code>string keyNamesPermaKilled = 6;</code>
     */
    protected $keyNamesPermaKilled = '';
    /**
     * Generated from protobuf field <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>int64 time = 8;</code>
     */
    protected $time = 0;
    /**
     * computed
     *
     * Generated from protobuf field <code>int64 uptime = 9;</code>
     */
    protected $uptime = 0;
    /**
     * computed
     *
     * Generated from protobuf field <code>float avgKeysServedPerMin = 10;</code>
     */
    protected $avgKeysServedPerMin = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $serverVersion
     *           keys.ServerVersion
     *     @type int $keyExhaustions
     *           keys.TotalExhaustions
     *     @type int|string $totalAvailableUsesPerMin
     *           keys.TotalPerMinute
     *     @type int|string $totalKeysServed
     *           keys.TotalKeysServed
     *     @type int|string $totalKeysKilled
     *           computed
     *     @type string $keyNamesPermaKilled
     *     @type \Apikeyserver\KeyDetailsResponse[]|\Google\Protobuf\Internal\RepeatedField $items
     *     @type int|string $time
     *     @type int|string $uptime
     *           computed
     *     @type float $avgKeysServedPerMin
     *           computed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ApiKeyServer::initOnce();
        parent::__construct($data);
    }

    /**
     * keys.ServerVersion
     *
     * Generated from protobuf field <code>string serverVersion = 1;</code>
     * @return string
     */
    public function getServerVersion()
    {
        return $this->serverVersion;
    }

    /**
     * keys.ServerVersion
     *
     * Generated from protobuf field <code>string serverVersion = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServerVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverVersion = $var;

        return $this;
    }

    /**
     * keys.TotalExhaustions
     *
     * Generated from protobuf field <code>uint32 keyExhaustions = 2;</code>
     * @return int
     */
    public function getKeyExhaustions()
    {
        return $this->keyExhaustions;
    }

    /**
     * keys.TotalExhaustions
     *
     * Generated from protobuf field <code>uint32 keyExhaustions = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyExhaustions($var)
    {
        GPBUtil::checkUint32($var);
        $this->keyExhaustions = $var;

        return $this;
    }

    /**
     * keys.TotalPerMinute
     *
     * Generated from protobuf field <code>uint64 totalAvailableUsesPerMin = 3;</code>
     * @return int|string
     */
    public function getTotalAvailableUsesPerMin()
    {
        return $this->totalAvailableUsesPerMin;
    }

    /**
     * keys.TotalPerMinute
     *
     * Generated from protobuf field <code>uint64 totalAvailableUsesPerMin = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalAvailableUsesPerMin($var)
    {
        GPBUtil::checkUint64($var);
        $this->totalAvailableUsesPerMin = $var;

        return $this;
    }

    /**
     * keys.TotalKeysServed
     *
     * Generated from protobuf field <code>uint64 totalKeysServed = 4;</code>
     * @return int|string
     */
    public function getTotalKeysServed()
    {
        return $this->totalKeysServed;
    }

    /**
     * keys.TotalKeysServed
     *
     * Generated from protobuf field <code>uint64 totalKeysServed = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalKeysServed($var)
    {
        GPBUtil::checkUint64($var);
        $this->totalKeysServed = $var;

        return $this;
    }

    /**
     * computed
     *
     * Generated from protobuf field <code>uint64 totalKeysKilled = 5;</code>
     * @return int|string
     */
    public function getTotalKeysKilled()
    {
        return $this->totalKeysKilled;
    }

    /**
     * computed
     *
     * Generated from protobuf field <code>uint64 totalKeysKilled = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalKeysKilled($var)
    {
        GPBUtil::checkUint64($var);
        $this->totalKeysKilled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string keyNamesPermaKilled = 6;</code>
     * @return string
     */
    public function getKeyNamesPermaKilled()
    {
        return $this->keyNamesPermaKilled;
    }

    /**
     * Generated from protobuf field <code>string keyNamesPermaKilled = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyNamesPermaKilled($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyNamesPermaKilled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     * @param \Apikeyserver\KeyDetailsResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Apikeyserver\KeyDetailsResponse::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 time = 8;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int64 time = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * computed
     *
     * Generated from protobuf field <code>int64 uptime = 9;</code>
     * @return int|string
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * computed
     *
     * Generated from protobuf field <code>int64 uptime = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkInt64($var);
        $this->uptime = $var;

        return $this;
    }

    /**
     * computed
     *
     * Generated from protobuf field <code>float avgKeysServedPerMin = 10;</code>
     * @return float
     */
    public function getAvgKeysServedPerMin()
    {
        return $this->avgKeysServedPerMin;
    }

    /**
     * computed
     *
     * Generated from protobuf field <code>float avgKeysServedPerMin = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgKeysServedPerMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->avgKeysServedPerMin = $var;

        return $this;
    }

}

