<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

namespace Apikeyserver;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * sub-response on the details of each key for GetServerInfoResponse
 *
 * Generated from protobuf message <code>apikeyserver.KeyDetailsResponse</code>
 */
class KeyDetailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string types = 2;</code>
     */
    protected $types = '';
    /**
     * Generated from protobuf field <code>uint32 uses = 3;</code>
     */
    protected $uses = 0;
    /**
     * Generated from protobuf field <code>uint32 kills = 4;</code>
     */
    protected $kills = 0;
    /**
     * Generated from protobuf field <code>bool active = 5;</code>
     */
    protected $active = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $types
     *     @type int $uses
     *     @type int $kills
     *     @type bool $active
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ApiKeyServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string types = 2;</code>
     * @return string
     */
    public function getTypes()
    {
        return $this->types;
    }

    /**
     * Generated from protobuf field <code>string types = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTypes($var)
    {
        GPBUtil::checkString($var, True);
        $this->types = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uses = 3;</code>
     * @return int
     */
    public function getUses()
    {
        return $this->uses;
    }

    /**
     * Generated from protobuf field <code>uint32 uses = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUses($var)
    {
        GPBUtil::checkUint32($var);
        $this->uses = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 kills = 4;</code>
     * @return int
     */
    public function getKills()
    {
        return $this->kills;
    }

    /**
     * Generated from protobuf field <code>uint32 kills = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setKills($var)
    {
        GPBUtil::checkUint32($var);
        $this->kills = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool active = 5;</code>
     * @return bool
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Generated from protobuf field <code>bool active = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;

        return $this;
    }

}

