<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

namespace Apikeyserver;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request a key be killed for until t Time
 *
 * Generated from protobuf message <code>apikeyserver.RequestTimedKillKey</code>
 */
class RequestTimedKillKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string requester = 1;</code>
     */
    protected $requester = '';
    /**
     * Generated from protobuf field <code>string key = 2;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     */
    protected $time = 0;
    /**
     * time when key will be returned to service
     *
     * Generated from protobuf field <code>int64 returnTime = 5;</code>
     */
    protected $returnTime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requester
     *     @type string $key
     *     @type string $name
     *     @type int|string $time
     *           unixNano
     *     @type int|string $returnTime
     *           time when key will be returned to service
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ApiKeyServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string requester = 1;</code>
     * @return string
     */
    public function getRequester()
    {
        return $this->requester;
    }

    /**
     * Generated from protobuf field <code>string requester = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequester($var)
    {
        GPBUtil::checkString($var, True);
        $this->requester = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * unixNano
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * time when key will be returned to service
     *
     * Generated from protobuf field <code>int64 returnTime = 5;</code>
     * @return int|string
     */
    public function getReturnTime()
    {
        return $this->returnTime;
    }

    /**
     * time when key will be returned to service
     *
     * Generated from protobuf field <code>int64 returnTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReturnTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->returnTime = $var;

        return $this;
    }

}

