<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

namespace Apikeyserver;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>apikeyserver.TimedKillResponse</code>
 */
class TimedKillResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.apikeyserver.GenericKillResponse result = 1;</code>
     */
    protected $result = null;
    /**
     *unixNano
     *
     * Generated from protobuf field <code>int64 returnToService = 2;</code>
     */
    protected $returnToService = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Apikeyserver\GenericKillResponse $result
     *     @type int|string $returnToService
     *          unixNano
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ApiKeyServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.apikeyserver.GenericKillResponse result = 1;</code>
     * @return \Apikeyserver\GenericKillResponse
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.apikeyserver.GenericKillResponse result = 1;</code>
     * @param \Apikeyserver\GenericKillResponse $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Apikeyserver\GenericKillResponse::class);
        $this->result = $var;

        return $this;
    }

    /**
     *unixNano
     *
     * Generated from protobuf field <code>int64 returnToService = 2;</code>
     * @return int|string
     */
    public function getReturnToService()
    {
        return $this->returnToService;
    }

    /**
     *unixNano
     *
     * Generated from protobuf field <code>int64 returnToService = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReturnToService($var)
    {
        GPBUtil::checkInt64($var);
        $this->returnToService = $var;

        return $this;
    }

}

