// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public final class apiKeyServer {
  private apiKeyServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_RequestKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_RequestKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_RequestServerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_RequestServerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_GetKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_GetKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_KeyResponseRemaining_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_KeyResponseRemaining_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_KeyResponseTypeNames_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_KeyResponseTypeNames_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_RequestKillKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_RequestKillKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_RequestPermKillKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_RequestPermKillKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_GenericKillResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_GenericKillResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_GetServerInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_GetServerInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apikeyserver_KeyDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apikeyserver_KeyDetailsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037apikeyserver/apiKeyServer.proto\022\014apike" +
      "yserver\032 google/protobuf/field_mask.prot" +
      "o\"w\n\nRequestKey\022\021\n\trequester\030\001 \001(\t\022\014\n\004ty" +
      "pe\030\002 \001(\t\022\030\n\020acceptExhaustion\030\003 \001(\010\022.\n\nfi" +
      "eld_mask\030\004 \001(\0132\032.google.protobuf.FieldMa" +
      "sk\"V\n\021RequestServerInfo\022\021\n\trequester\030\001 \001" +
      "(\t\022.\n\nfield_mask\030\002 \001(\0132\032.google.protobuf" +
      ".FieldMask\"\215\001\n\016GetKeyResponse\022\013\n\003key\030\001 \001" +
      "(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\014\n\004time\030\004" +
      " \001(\003\0221\n\005items\030\005 \003(\0132\".apikeyserver.KeyRe" +
      "sponseRemaining\022\021\n\texhausted\030\006 \001(\010\"K\n\024Ke" +
      "yResponseRemaining\022\034\n\024KeyResponseTypeNam" +
      "es\030\001 \001(\t\022\025\n\rtypeRemaining\030\002 \001(\r\"(\n\024KeyRe" +
      "sponseTypeNames\022\020\n\010typeName\030\001 \001(\t\"L\n\016Req" +
      "uestKillKey\022\021\n\trequester\030\001 \001(\t\022\013\n\003key\030\002 " +
      "\001(\t\022\014\n\004name\030\003 \001(\t\022\014\n\004time\030\004 \001(\003\"P\n\022Reque" +
      "stPermKillKey\022\021\n\trequester\030\001 \001(\t\022\013\n\003key\030" +
      "\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\014\n\004time\030\004 \001(\003\"3\n\023Gen" +
      "ericKillResponse\022\016\n\006result\030\001 \001(\010\022\014\n\004time" +
      "\030\002 \001(\003\"\243\002\n\025GetServerInfoResponse\022\025\n\rserv" +
      "erVersion\030\001 \001(\t\022\026\n\016keyExhaustions\030\002 \001(\r\022" +
      " \n\030totalAvailableUsesPerMin\030\003 \001(\004\022\027\n\017tot" +
      "alKeysServed\030\004 \001(\004\022\027\n\017totalKeysKilled\030\005 " +
      "\001(\004\022\033\n\023keyNamesPermaKilled\030\006 \001(\t\022/\n\005item" +
      "s\030\007 \003(\0132 .apikeyserver.KeyDetailsRespons" +
      "e\022\014\n\004time\030\010 \001(\003\022\016\n\006uptime\030\t \001(\003\022\033\n\023avgKe" +
      "ysServedPerMin\030\n \001(\002\"^\n\022KeyDetailsRespon" +
      "se\022\014\n\004name\030\001 \001(\t\022\r\n\005types\030\002 \001(\t\022\014\n\004uses\030" +
      "\003 \001(\r\022\r\n\005kills\030\004 \001(\r\022\016\n\006active\030\005 \001(\0102\317\002\n" +
      "\014ApiKeyServer\022B\n\006GetKey\022\030.apikeyserver.R" +
      "equestKey\032\034.apikeyserver.GetKeyResponse\"" +
      "\000\022L\n\007KillKey\022\034.apikeyserver.RequestKillK" +
      "ey\032!.apikeyserver.GenericKillResponse\"\000\022" +
      "T\n\013PermKillKey\022 .apikeyserver.RequestPer" +
      "mKillKey\032!.apikeyserver.GenericKillRespo" +
      "nse\"\000\022W\n\rGetServerInfo\022\037.apikeyserver.Re" +
      "questServerInfo\032#.apikeyserver.GetServer" +
      "InfoResponse\"\000B&\n\004mainB\014apiKeyServerP\001Z\016" +
      "./apikeyserverb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.FieldMaskProto.getDescriptor(),
        });
    internal_static_apikeyserver_RequestKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apikeyserver_RequestKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_RequestKey_descriptor,
        new java.lang.String[] { "Requester", "Type", "AcceptExhaustion", "FieldMask", });
    internal_static_apikeyserver_RequestServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apikeyserver_RequestServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_RequestServerInfo_descriptor,
        new java.lang.String[] { "Requester", "FieldMask", });
    internal_static_apikeyserver_GetKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apikeyserver_GetKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_GetKeyResponse_descriptor,
        new java.lang.String[] { "Key", "Name", "Type", "Time", "Items", "Exhausted", });
    internal_static_apikeyserver_KeyResponseRemaining_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apikeyserver_KeyResponseRemaining_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_KeyResponseRemaining_descriptor,
        new java.lang.String[] { "KeyResponseTypeNames", "TypeRemaining", });
    internal_static_apikeyserver_KeyResponseTypeNames_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_apikeyserver_KeyResponseTypeNames_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_KeyResponseTypeNames_descriptor,
        new java.lang.String[] { "TypeName", });
    internal_static_apikeyserver_RequestKillKey_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_apikeyserver_RequestKillKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_RequestKillKey_descriptor,
        new java.lang.String[] { "Requester", "Key", "Name", "Time", });
    internal_static_apikeyserver_RequestPermKillKey_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_apikeyserver_RequestPermKillKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_RequestPermKillKey_descriptor,
        new java.lang.String[] { "Requester", "Key", "Name", "Time", });
    internal_static_apikeyserver_GenericKillResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_apikeyserver_GenericKillResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_GenericKillResponse_descriptor,
        new java.lang.String[] { "Result", "Time", });
    internal_static_apikeyserver_GetServerInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_apikeyserver_GetServerInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_GetServerInfoResponse_descriptor,
        new java.lang.String[] { "ServerVersion", "KeyExhaustions", "TotalAvailableUsesPerMin", "TotalKeysServed", "TotalKeysKilled", "KeyNamesPermaKilled", "Items", "Time", "Uptime", "AvgKeysServedPerMin", });
    internal_static_apikeyserver_KeyDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_apikeyserver_KeyDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apikeyserver_KeyDetailsResponse_descriptor,
        new java.lang.String[] { "Name", "Types", "Uses", "Kills", "Active", });
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
