// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public interface GetKeyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikeyserver.GetKeyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * unixNano
   * </pre>
   *
   * <code>int64 time = 4;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
   */
  java.util.List<main.KeyResponseRemaining> 
      getItemsList();
  /**
   * <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
   */
  main.KeyResponseRemaining getItems(int index);
  /**
   * <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
   */
  java.util.List<? extends main.KeyResponseRemainingOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .apikeyserver.KeyResponseRemaining items = 5;</code>
   */
  main.KeyResponseRemainingOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <pre>
   * no keys remaining
   * </pre>
   *
   * <code>bool exhausted = 6;</code>
   * @return The exhausted.
   */
  boolean getExhausted();
}
