// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

/**
 * <pre>
 * response for RequestServerInfo
 * </pre>
 *
 * Protobuf type {@code apikeyserver.GetServerInfoResponse}
 */
public  final class GetServerInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apikeyserver.GetServerInfoResponse)
    GetServerInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetServerInfoResponse.newBuilder() to construct.
  private GetServerInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetServerInfoResponse() {
    serverVersion_ = "";
    keyNamesPermaKilled_ = "";
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetServerInfoResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetServerInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serverVersion_ = s;
            break;
          }
          case 16: {

            keyExhaustions_ = input.readUInt32();
            break;
          }
          case 24: {

            totalAvailableUsesPerMin_ = input.readUInt64();
            break;
          }
          case 32: {

            totalKeysServed_ = input.readUInt64();
            break;
          }
          case 40: {

            totalKeysKilled_ = input.readUInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            keyNamesPermaKilled_ = s;
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<main.KeyDetailsResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(main.KeyDetailsResponse.parser(), extensionRegistry));
            break;
          }
          case 64: {

            time_ = input.readInt64();
            break;
          }
          case 72: {

            uptime_ = input.readInt64();
            break;
          }
          case 85: {

            avgKeysServedPerMin_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.apiKeyServer.internal_static_apikeyserver_GetServerInfoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.apiKeyServer.internal_static_apikeyserver_GetServerInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.GetServerInfoResponse.class, main.GetServerInfoResponse.Builder.class);
  }

  public static final int SERVERVERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object serverVersion_;
  /**
   * <pre>
   * keys.ServerVersion
   * </pre>
   *
   * <code>string serverVersion = 1;</code>
   * @return The serverVersion.
   */
  public java.lang.String getServerVersion() {
    java.lang.Object ref = serverVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * keys.ServerVersion
   * </pre>
   *
   * <code>string serverVersion = 1;</code>
   * @return The bytes for serverVersion.
   */
  public com.google.protobuf.ByteString
      getServerVersionBytes() {
    java.lang.Object ref = serverVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYEXHAUSTIONS_FIELD_NUMBER = 2;
  private int keyExhaustions_;
  /**
   * <pre>
   * keys.TotalExhaustions
   * </pre>
   *
   * <code>uint32 keyExhaustions = 2;</code>
   * @return The keyExhaustions.
   */
  public int getKeyExhaustions() {
    return keyExhaustions_;
  }

  public static final int TOTALAVAILABLEUSESPERMIN_FIELD_NUMBER = 3;
  private long totalAvailableUsesPerMin_;
  /**
   * <pre>
   * keys.TotalPerMinute
   * </pre>
   *
   * <code>uint64 totalAvailableUsesPerMin = 3;</code>
   * @return The totalAvailableUsesPerMin.
   */
  public long getTotalAvailableUsesPerMin() {
    return totalAvailableUsesPerMin_;
  }

  public static final int TOTALKEYSSERVED_FIELD_NUMBER = 4;
  private long totalKeysServed_;
  /**
   * <pre>
   * keys.TotalKeysServed
   * </pre>
   *
   * <code>uint64 totalKeysServed = 4;</code>
   * @return The totalKeysServed.
   */
  public long getTotalKeysServed() {
    return totalKeysServed_;
  }

  public static final int TOTALKEYSKILLED_FIELD_NUMBER = 5;
  private long totalKeysKilled_;
  /**
   * <pre>
   * computed
   * </pre>
   *
   * <code>uint64 totalKeysKilled = 5;</code>
   * @return The totalKeysKilled.
   */
  public long getTotalKeysKilled() {
    return totalKeysKilled_;
  }

  public static final int KEYNAMESPERMAKILLED_FIELD_NUMBER = 6;
  private volatile java.lang.Object keyNamesPermaKilled_;
  /**
   * <code>string keyNamesPermaKilled = 6;</code>
   * @return The keyNamesPermaKilled.
   */
  public java.lang.String getKeyNamesPermaKilled() {
    java.lang.Object ref = keyNamesPermaKilled_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyNamesPermaKilled_ = s;
      return s;
    }
  }
  /**
   * <code>string keyNamesPermaKilled = 6;</code>
   * @return The bytes for keyNamesPermaKilled.
   */
  public com.google.protobuf.ByteString
      getKeyNamesPermaKilledBytes() {
    java.lang.Object ref = keyNamesPermaKilled_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyNamesPermaKilled_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEMS_FIELD_NUMBER = 7;
  private java.util.List<main.KeyDetailsResponse> items_;
  /**
   * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
   */
  public java.util.List<main.KeyDetailsResponse> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
   */
  public java.util.List<? extends main.KeyDetailsResponseOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
   */
  public main.KeyDetailsResponse getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
   */
  public main.KeyDetailsResponseOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int TIME_FIELD_NUMBER = 8;
  private long time_;
  /**
   * <code>int64 time = 8;</code>
   * @return The time.
   */
  public long getTime() {
    return time_;
  }

  public static final int UPTIME_FIELD_NUMBER = 9;
  private long uptime_;
  /**
   * <pre>
   * computed
   * </pre>
   *
   * <code>int64 uptime = 9;</code>
   * @return The uptime.
   */
  public long getUptime() {
    return uptime_;
  }

  public static final int AVGKEYSSERVEDPERMIN_FIELD_NUMBER = 10;
  private float avgKeysServedPerMin_;
  /**
   * <pre>
   * computed
   * </pre>
   *
   * <code>float avgKeysServedPerMin = 10;</code>
   * @return The avgKeysServedPerMin.
   */
  public float getAvgKeysServedPerMin() {
    return avgKeysServedPerMin_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServerVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverVersion_);
    }
    if (keyExhaustions_ != 0) {
      output.writeUInt32(2, keyExhaustions_);
    }
    if (totalAvailableUsesPerMin_ != 0L) {
      output.writeUInt64(3, totalAvailableUsesPerMin_);
    }
    if (totalKeysServed_ != 0L) {
      output.writeUInt64(4, totalKeysServed_);
    }
    if (totalKeysKilled_ != 0L) {
      output.writeUInt64(5, totalKeysKilled_);
    }
    if (!getKeyNamesPermaKilledBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, keyNamesPermaKilled_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(7, items_.get(i));
    }
    if (time_ != 0L) {
      output.writeInt64(8, time_);
    }
    if (uptime_ != 0L) {
      output.writeInt64(9, uptime_);
    }
    if (avgKeysServedPerMin_ != 0F) {
      output.writeFloat(10, avgKeysServedPerMin_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServerVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverVersion_);
    }
    if (keyExhaustions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, keyExhaustions_);
    }
    if (totalAvailableUsesPerMin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, totalAvailableUsesPerMin_);
    }
    if (totalKeysServed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, totalKeysServed_);
    }
    if (totalKeysKilled_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, totalKeysKilled_);
    }
    if (!getKeyNamesPermaKilledBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, keyNamesPermaKilled_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, items_.get(i));
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, time_);
    }
    if (uptime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, uptime_);
    }
    if (avgKeysServedPerMin_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, avgKeysServedPerMin_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof main.GetServerInfoResponse)) {
      return super.equals(obj);
    }
    main.GetServerInfoResponse other = (main.GetServerInfoResponse) obj;

    if (!getServerVersion()
        .equals(other.getServerVersion())) return false;
    if (getKeyExhaustions()
        != other.getKeyExhaustions()) return false;
    if (getTotalAvailableUsesPerMin()
        != other.getTotalAvailableUsesPerMin()) return false;
    if (getTotalKeysServed()
        != other.getTotalKeysServed()) return false;
    if (getTotalKeysKilled()
        != other.getTotalKeysKilled()) return false;
    if (!getKeyNamesPermaKilled()
        .equals(other.getKeyNamesPermaKilled())) return false;
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (getTime()
        != other.getTime()) return false;
    if (getUptime()
        != other.getUptime()) return false;
    if (java.lang.Float.floatToIntBits(getAvgKeysServedPerMin())
        != java.lang.Float.floatToIntBits(
            other.getAvgKeysServedPerMin())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVERVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getServerVersion().hashCode();
    hash = (37 * hash) + KEYEXHAUSTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getKeyExhaustions();
    hash = (37 * hash) + TOTALAVAILABLEUSESPERMIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalAvailableUsesPerMin());
    hash = (37 * hash) + TOTALKEYSSERVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalKeysServed());
    hash = (37 * hash) + TOTALKEYSKILLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalKeysKilled());
    hash = (37 * hash) + KEYNAMESPERMAKILLED_FIELD_NUMBER;
    hash = (53 * hash) + getKeyNamesPermaKilled().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + UPTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUptime());
    hash = (37 * hash) + AVGKEYSSERVEDPERMIN_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAvgKeysServedPerMin());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static main.GetServerInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.GetServerInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.GetServerInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.GetServerInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.GetServerInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.GetServerInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.GetServerInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.GetServerInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.GetServerInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static main.GetServerInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.GetServerInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.GetServerInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.GetServerInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * response for RequestServerInfo
   * </pre>
   *
   * Protobuf type {@code apikeyserver.GetServerInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apikeyserver.GetServerInfoResponse)
      main.GetServerInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.apiKeyServer.internal_static_apikeyserver_GetServerInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.apiKeyServer.internal_static_apikeyserver_GetServerInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.GetServerInfoResponse.class, main.GetServerInfoResponse.Builder.class);
    }

    // Construct using main.GetServerInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serverVersion_ = "";

      keyExhaustions_ = 0;

      totalAvailableUsesPerMin_ = 0L;

      totalKeysServed_ = 0L;

      totalKeysKilled_ = 0L;

      keyNamesPermaKilled_ = "";

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      time_ = 0L;

      uptime_ = 0L;

      avgKeysServedPerMin_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.apiKeyServer.internal_static_apikeyserver_GetServerInfoResponse_descriptor;
    }

    @java.lang.Override
    public main.GetServerInfoResponse getDefaultInstanceForType() {
      return main.GetServerInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public main.GetServerInfoResponse build() {
      main.GetServerInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public main.GetServerInfoResponse buildPartial() {
      main.GetServerInfoResponse result = new main.GetServerInfoResponse(this);
      int from_bitField0_ = bitField0_;
      result.serverVersion_ = serverVersion_;
      result.keyExhaustions_ = keyExhaustions_;
      result.totalAvailableUsesPerMin_ = totalAvailableUsesPerMin_;
      result.totalKeysServed_ = totalKeysServed_;
      result.totalKeysKilled_ = totalKeysKilled_;
      result.keyNamesPermaKilled_ = keyNamesPermaKilled_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.time_ = time_;
      result.uptime_ = uptime_;
      result.avgKeysServedPerMin_ = avgKeysServedPerMin_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.GetServerInfoResponse) {
        return mergeFrom((main.GetServerInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.GetServerInfoResponse other) {
      if (other == main.GetServerInfoResponse.getDefaultInstance()) return this;
      if (!other.getServerVersion().isEmpty()) {
        serverVersion_ = other.serverVersion_;
        onChanged();
      }
      if (other.getKeyExhaustions() != 0) {
        setKeyExhaustions(other.getKeyExhaustions());
      }
      if (other.getTotalAvailableUsesPerMin() != 0L) {
        setTotalAvailableUsesPerMin(other.getTotalAvailableUsesPerMin());
      }
      if (other.getTotalKeysServed() != 0L) {
        setTotalKeysServed(other.getTotalKeysServed());
      }
      if (other.getTotalKeysKilled() != 0L) {
        setTotalKeysKilled(other.getTotalKeysKilled());
      }
      if (!other.getKeyNamesPermaKilled().isEmpty()) {
        keyNamesPermaKilled_ = other.keyNamesPermaKilled_;
        onChanged();
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getUptime() != 0L) {
        setUptime(other.getUptime());
      }
      if (other.getAvgKeysServedPerMin() != 0F) {
        setAvgKeysServedPerMin(other.getAvgKeysServedPerMin());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.GetServerInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.GetServerInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object serverVersion_ = "";
    /**
     * <pre>
     * keys.ServerVersion
     * </pre>
     *
     * <code>string serverVersion = 1;</code>
     * @return The serverVersion.
     */
    public java.lang.String getServerVersion() {
      java.lang.Object ref = serverVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * keys.ServerVersion
     * </pre>
     *
     * <code>string serverVersion = 1;</code>
     * @return The bytes for serverVersion.
     */
    public com.google.protobuf.ByteString
        getServerVersionBytes() {
      java.lang.Object ref = serverVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * keys.ServerVersion
     * </pre>
     *
     * <code>string serverVersion = 1;</code>
     * @param value The serverVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServerVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * keys.ServerVersion
     * </pre>
     *
     * <code>string serverVersion = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerVersion() {
      
      serverVersion_ = getDefaultInstance().getServerVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * keys.ServerVersion
     * </pre>
     *
     * <code>string serverVersion = 1;</code>
     * @param value The bytes for serverVersion to set.
     * @return This builder for chaining.
     */
    public Builder setServerVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverVersion_ = value;
      onChanged();
      return this;
    }

    private int keyExhaustions_ ;
    /**
     * <pre>
     * keys.TotalExhaustions
     * </pre>
     *
     * <code>uint32 keyExhaustions = 2;</code>
     * @return The keyExhaustions.
     */
    public int getKeyExhaustions() {
      return keyExhaustions_;
    }
    /**
     * <pre>
     * keys.TotalExhaustions
     * </pre>
     *
     * <code>uint32 keyExhaustions = 2;</code>
     * @param value The keyExhaustions to set.
     * @return This builder for chaining.
     */
    public Builder setKeyExhaustions(int value) {
      
      keyExhaustions_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * keys.TotalExhaustions
     * </pre>
     *
     * <code>uint32 keyExhaustions = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyExhaustions() {
      
      keyExhaustions_ = 0;
      onChanged();
      return this;
    }

    private long totalAvailableUsesPerMin_ ;
    /**
     * <pre>
     * keys.TotalPerMinute
     * </pre>
     *
     * <code>uint64 totalAvailableUsesPerMin = 3;</code>
     * @return The totalAvailableUsesPerMin.
     */
    public long getTotalAvailableUsesPerMin() {
      return totalAvailableUsesPerMin_;
    }
    /**
     * <pre>
     * keys.TotalPerMinute
     * </pre>
     *
     * <code>uint64 totalAvailableUsesPerMin = 3;</code>
     * @param value The totalAvailableUsesPerMin to set.
     * @return This builder for chaining.
     */
    public Builder setTotalAvailableUsesPerMin(long value) {
      
      totalAvailableUsesPerMin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * keys.TotalPerMinute
     * </pre>
     *
     * <code>uint64 totalAvailableUsesPerMin = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalAvailableUsesPerMin() {
      
      totalAvailableUsesPerMin_ = 0L;
      onChanged();
      return this;
    }

    private long totalKeysServed_ ;
    /**
     * <pre>
     * keys.TotalKeysServed
     * </pre>
     *
     * <code>uint64 totalKeysServed = 4;</code>
     * @return The totalKeysServed.
     */
    public long getTotalKeysServed() {
      return totalKeysServed_;
    }
    /**
     * <pre>
     * keys.TotalKeysServed
     * </pre>
     *
     * <code>uint64 totalKeysServed = 4;</code>
     * @param value The totalKeysServed to set.
     * @return This builder for chaining.
     */
    public Builder setTotalKeysServed(long value) {
      
      totalKeysServed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * keys.TotalKeysServed
     * </pre>
     *
     * <code>uint64 totalKeysServed = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalKeysServed() {
      
      totalKeysServed_ = 0L;
      onChanged();
      return this;
    }

    private long totalKeysKilled_ ;
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>uint64 totalKeysKilled = 5;</code>
     * @return The totalKeysKilled.
     */
    public long getTotalKeysKilled() {
      return totalKeysKilled_;
    }
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>uint64 totalKeysKilled = 5;</code>
     * @param value The totalKeysKilled to set.
     * @return This builder for chaining.
     */
    public Builder setTotalKeysKilled(long value) {
      
      totalKeysKilled_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>uint64 totalKeysKilled = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalKeysKilled() {
      
      totalKeysKilled_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object keyNamesPermaKilled_ = "";
    /**
     * <code>string keyNamesPermaKilled = 6;</code>
     * @return The keyNamesPermaKilled.
     */
    public java.lang.String getKeyNamesPermaKilled() {
      java.lang.Object ref = keyNamesPermaKilled_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyNamesPermaKilled_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string keyNamesPermaKilled = 6;</code>
     * @return The bytes for keyNamesPermaKilled.
     */
    public com.google.protobuf.ByteString
        getKeyNamesPermaKilledBytes() {
      java.lang.Object ref = keyNamesPermaKilled_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyNamesPermaKilled_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string keyNamesPermaKilled = 6;</code>
     * @param value The keyNamesPermaKilled to set.
     * @return This builder for chaining.
     */
    public Builder setKeyNamesPermaKilled(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keyNamesPermaKilled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string keyNamesPermaKilled = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyNamesPermaKilled() {
      
      keyNamesPermaKilled_ = getDefaultInstance().getKeyNamesPermaKilled();
      onChanged();
      return this;
    }
    /**
     * <code>string keyNamesPermaKilled = 6;</code>
     * @param value The bytes for keyNamesPermaKilled to set.
     * @return This builder for chaining.
     */
    public Builder setKeyNamesPermaKilledBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      keyNamesPermaKilled_ = value;
      onChanged();
      return this;
    }

    private java.util.List<main.KeyDetailsResponse> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<main.KeyDetailsResponse>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        main.KeyDetailsResponse, main.KeyDetailsResponse.Builder, main.KeyDetailsResponseOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public java.util.List<main.KeyDetailsResponse> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public main.KeyDetailsResponse getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder setItems(
        int index, main.KeyDetailsResponse value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder setItems(
        int index, main.KeyDetailsResponse.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder addItems(main.KeyDetailsResponse value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder addItems(
        int index, main.KeyDetailsResponse value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder addItems(
        main.KeyDetailsResponse.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder addItems(
        int index, main.KeyDetailsResponse.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends main.KeyDetailsResponse> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public main.KeyDetailsResponse.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public main.KeyDetailsResponseOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public java.util.List<? extends main.KeyDetailsResponseOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public main.KeyDetailsResponse.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          main.KeyDetailsResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public main.KeyDetailsResponse.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, main.KeyDetailsResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .apikeyserver.KeyDetailsResponse items = 7;</code>
     */
    public java.util.List<main.KeyDetailsResponse.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        main.KeyDetailsResponse, main.KeyDetailsResponse.Builder, main.KeyDetailsResponseOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            main.KeyDetailsResponse, main.KeyDetailsResponse.Builder, main.KeyDetailsResponseOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private long time_ ;
    /**
     * <code>int64 time = 8;</code>
     * @return The time.
     */
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 8;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long uptime_ ;
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>int64 uptime = 9;</code>
     * @return The uptime.
     */
    public long getUptime() {
      return uptime_;
    }
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>int64 uptime = 9;</code>
     * @param value The uptime to set.
     * @return This builder for chaining.
     */
    public Builder setUptime(long value) {
      
      uptime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>int64 uptime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUptime() {
      
      uptime_ = 0L;
      onChanged();
      return this;
    }

    private float avgKeysServedPerMin_ ;
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>float avgKeysServedPerMin = 10;</code>
     * @return The avgKeysServedPerMin.
     */
    public float getAvgKeysServedPerMin() {
      return avgKeysServedPerMin_;
    }
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>float avgKeysServedPerMin = 10;</code>
     * @param value The avgKeysServedPerMin to set.
     * @return This builder for chaining.
     */
    public Builder setAvgKeysServedPerMin(float value) {
      
      avgKeysServedPerMin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * computed
     * </pre>
     *
     * <code>float avgKeysServedPerMin = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgKeysServedPerMin() {
      
      avgKeysServedPerMin_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apikeyserver.GetServerInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:apikeyserver.GetServerInfoResponse)
  private static final main.GetServerInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.GetServerInfoResponse();
  }

  public static main.GetServerInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetServerInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetServerInfoResponse>() {
    @java.lang.Override
    public GetServerInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetServerInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetServerInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetServerInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public main.GetServerInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

