// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public interface KeyDetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikeyserver.KeyDetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string types = 2;</code>
   * @return The types.
   */
  java.lang.String getTypes();
  /**
   * <code>string types = 2;</code>
   * @return The bytes for types.
   */
  com.google.protobuf.ByteString
      getTypesBytes();

  /**
   * <code>uint32 uses = 3;</code>
   * @return The uses.
   */
  int getUses();

  /**
   * <code>uint32 kills = 4;</code>
   * @return The kills.
   */
  int getKills();

  /**
   * <code>bool active = 5;</code>
   * @return The active.
   */
  boolean getActive();
}
