// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public interface KeyResponseTypeNamesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikeyserver.KeyResponseTypeNames)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string typeName = 1;</code>
   * @return The typeName.
   */
  java.lang.String getTypeName();
  /**
   * <code>string typeName = 1;</code>
   * @return The bytes for typeName.
   */
  com.google.protobuf.ByteString
      getTypeNameBytes();
}
