// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public interface KeyResponseRemainingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikeyserver.KeyResponseRemaining)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string KeyResponseTypeNames = 1;</code>
   * @return The keyResponseTypeNames.
   */
  java.lang.String getKeyResponseTypeNames();
  /**
   * <code>string KeyResponseTypeNames = 1;</code>
   * @return The bytes for keyResponseTypeNames.
   */
  com.google.protobuf.ByteString
      getKeyResponseTypeNamesBytes();

  /**
   * <code>uint32 typeRemaining = 2;</code>
   * @return The typeRemaining.
   */
  int getTypeRemaining();
}
