// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

/**
 * <pre>
 * sub-response for RequestKey
 * </pre>
 *
 * Protobuf type {@code apikeyserver.KeyResponseRemaining}
 */
public  final class KeyResponseRemaining extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apikeyserver.KeyResponseRemaining)
    KeyResponseRemainingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KeyResponseRemaining.newBuilder() to construct.
  private KeyResponseRemaining(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KeyResponseRemaining() {
    keyResponseTypeNames_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KeyResponseRemaining();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KeyResponseRemaining(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            keyResponseTypeNames_ = s;
            break;
          }
          case 16: {

            typeRemaining_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.apiKeyServer.internal_static_apikeyserver_KeyResponseRemaining_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.apiKeyServer.internal_static_apikeyserver_KeyResponseRemaining_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.KeyResponseRemaining.class, main.KeyResponseRemaining.Builder.class);
  }

  public static final int KEYRESPONSETYPENAMES_FIELD_NUMBER = 1;
  private volatile java.lang.Object keyResponseTypeNames_;
  /**
   * <code>string KeyResponseTypeNames = 1;</code>
   * @return The keyResponseTypeNames.
   */
  public java.lang.String getKeyResponseTypeNames() {
    java.lang.Object ref = keyResponseTypeNames_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyResponseTypeNames_ = s;
      return s;
    }
  }
  /**
   * <code>string KeyResponseTypeNames = 1;</code>
   * @return The bytes for keyResponseTypeNames.
   */
  public com.google.protobuf.ByteString
      getKeyResponseTypeNamesBytes() {
    java.lang.Object ref = keyResponseTypeNames_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyResponseTypeNames_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPEREMAINING_FIELD_NUMBER = 2;
  private int typeRemaining_;
  /**
   * <code>uint32 typeRemaining = 2;</code>
   * @return The typeRemaining.
   */
  public int getTypeRemaining() {
    return typeRemaining_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKeyResponseTypeNamesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keyResponseTypeNames_);
    }
    if (typeRemaining_ != 0) {
      output.writeUInt32(2, typeRemaining_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKeyResponseTypeNamesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, keyResponseTypeNames_);
    }
    if (typeRemaining_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, typeRemaining_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof main.KeyResponseRemaining)) {
      return super.equals(obj);
    }
    main.KeyResponseRemaining other = (main.KeyResponseRemaining) obj;

    if (!getKeyResponseTypeNames()
        .equals(other.getKeyResponseTypeNames())) return false;
    if (getTypeRemaining()
        != other.getTypeRemaining()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEYRESPONSETYPENAMES_FIELD_NUMBER;
    hash = (53 * hash) + getKeyResponseTypeNames().hashCode();
    hash = (37 * hash) + TYPEREMAINING_FIELD_NUMBER;
    hash = (53 * hash) + getTypeRemaining();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static main.KeyResponseRemaining parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.KeyResponseRemaining parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.KeyResponseRemaining parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.KeyResponseRemaining parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.KeyResponseRemaining parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.KeyResponseRemaining parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.KeyResponseRemaining parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.KeyResponseRemaining parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.KeyResponseRemaining parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static main.KeyResponseRemaining parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.KeyResponseRemaining parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.KeyResponseRemaining parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.KeyResponseRemaining prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * sub-response for RequestKey
   * </pre>
   *
   * Protobuf type {@code apikeyserver.KeyResponseRemaining}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apikeyserver.KeyResponseRemaining)
      main.KeyResponseRemainingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.apiKeyServer.internal_static_apikeyserver_KeyResponseRemaining_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.apiKeyServer.internal_static_apikeyserver_KeyResponseRemaining_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.KeyResponseRemaining.class, main.KeyResponseRemaining.Builder.class);
    }

    // Construct using main.KeyResponseRemaining.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      keyResponseTypeNames_ = "";

      typeRemaining_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.apiKeyServer.internal_static_apikeyserver_KeyResponseRemaining_descriptor;
    }

    @java.lang.Override
    public main.KeyResponseRemaining getDefaultInstanceForType() {
      return main.KeyResponseRemaining.getDefaultInstance();
    }

    @java.lang.Override
    public main.KeyResponseRemaining build() {
      main.KeyResponseRemaining result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public main.KeyResponseRemaining buildPartial() {
      main.KeyResponseRemaining result = new main.KeyResponseRemaining(this);
      result.keyResponseTypeNames_ = keyResponseTypeNames_;
      result.typeRemaining_ = typeRemaining_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.KeyResponseRemaining) {
        return mergeFrom((main.KeyResponseRemaining)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.KeyResponseRemaining other) {
      if (other == main.KeyResponseRemaining.getDefaultInstance()) return this;
      if (!other.getKeyResponseTypeNames().isEmpty()) {
        keyResponseTypeNames_ = other.keyResponseTypeNames_;
        onChanged();
      }
      if (other.getTypeRemaining() != 0) {
        setTypeRemaining(other.getTypeRemaining());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.KeyResponseRemaining parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.KeyResponseRemaining) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object keyResponseTypeNames_ = "";
    /**
     * <code>string KeyResponseTypeNames = 1;</code>
     * @return The keyResponseTypeNames.
     */
    public java.lang.String getKeyResponseTypeNames() {
      java.lang.Object ref = keyResponseTypeNames_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyResponseTypeNames_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string KeyResponseTypeNames = 1;</code>
     * @return The bytes for keyResponseTypeNames.
     */
    public com.google.protobuf.ByteString
        getKeyResponseTypeNamesBytes() {
      java.lang.Object ref = keyResponseTypeNames_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyResponseTypeNames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string KeyResponseTypeNames = 1;</code>
     * @param value The keyResponseTypeNames to set.
     * @return This builder for chaining.
     */
    public Builder setKeyResponseTypeNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keyResponseTypeNames_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string KeyResponseTypeNames = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyResponseTypeNames() {
      
      keyResponseTypeNames_ = getDefaultInstance().getKeyResponseTypeNames();
      onChanged();
      return this;
    }
    /**
     * <code>string KeyResponseTypeNames = 1;</code>
     * @param value The bytes for keyResponseTypeNames to set.
     * @return This builder for chaining.
     */
    public Builder setKeyResponseTypeNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      keyResponseTypeNames_ = value;
      onChanged();
      return this;
    }

    private int typeRemaining_ ;
    /**
     * <code>uint32 typeRemaining = 2;</code>
     * @return The typeRemaining.
     */
    public int getTypeRemaining() {
      return typeRemaining_;
    }
    /**
     * <code>uint32 typeRemaining = 2;</code>
     * @param value The typeRemaining to set.
     * @return This builder for chaining.
     */
    public Builder setTypeRemaining(int value) {
      
      typeRemaining_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 typeRemaining = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeRemaining() {
      
      typeRemaining_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apikeyserver.KeyResponseRemaining)
  }

  // @@protoc_insertion_point(class_scope:apikeyserver.KeyResponseRemaining)
  private static final main.KeyResponseRemaining DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.KeyResponseRemaining();
  }

  public static main.KeyResponseRemaining getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KeyResponseRemaining>
      PARSER = new com.google.protobuf.AbstractParser<KeyResponseRemaining>() {
    @java.lang.Override
    public KeyResponseRemaining parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KeyResponseRemaining(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KeyResponseRemaining> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KeyResponseRemaining> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public main.KeyResponseRemaining getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

