// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public interface RequestKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikeyserver.RequestKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requester = 1;</code>
   * @return The requester.
   */
  java.lang.String getRequester();
  /**
   * <code>string requester = 1;</code>
   * @return The bytes for requester.
   */
  com.google.protobuf.ByteString
      getRequesterBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * requester doesn't want to wait, and instead wishes be told there are no keys available
   * </pre>
   *
   * <code>bool acceptExhaustion = 3;</code>
   * @return The acceptExhaustion.
   */
  boolean getAcceptExhaustion();

  /**
   * <code>.google.protobuf.FieldMask field_mask = 4;</code>
   * @return Whether the fieldMask field is set.
   */
  boolean hasFieldMask();
  /**
   * <code>.google.protobuf.FieldMask field_mask = 4;</code>
   * @return The fieldMask.
   */
  com.google.protobuf.FieldMask getFieldMask();
  /**
   * <code>.google.protobuf.FieldMask field_mask = 4;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder();
}
