// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apikeyserver/apiKeyServer.proto

package main;

public interface RequestServerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apikeyserver.RequestServerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requester = 1;</code>
   * @return The requester.
   */
  java.lang.String getRequester();
  /**
   * <code>string requester = 1;</code>
   * @return The bytes for requester.
   */
  com.google.protobuf.ByteString
      getRequesterBytes();

  /**
   * <code>.google.protobuf.FieldMask field_mask = 2;</code>
   * @return Whether the fieldMask field is set.
   */
  boolean hasFieldMask();
  /**
   * <code>.google.protobuf.FieldMask field_mask = 2;</code>
   * @return The fieldMask.
   */
  com.google.protobuf.FieldMask getFieldMask();
  /**
   * <code>.google.protobuf.FieldMask field_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder();
}
