# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiKeyServer.proto

require 'google/protobuf'

require 'google/protobuf/field_mask_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("apiKeyServer.proto", :syntax => :proto3) do
    add_message "apikeyserver.RequestKey" do
      optional :requester, :string, 1
      optional :type, :string, 2
      optional :acceptExhaustion, :bool, 3
      optional :field_mask, :message, 4, "google.protobuf.FieldMask"
    end
    add_message "apikeyserver.RequestServerInfo" do
      optional :requester, :string, 1
      optional :field_mask, :message, 2, "google.protobuf.FieldMask"
    end
    add_message "apikeyserver.GetKeyResponse" do
      optional :key, :string, 1
      optional :name, :string, 2
      optional :type, :string, 3
      optional :time, :int64, 4
      repeated :items, :message, 5, "apikeyserver.KeyResponseRemaining"
      optional :exhausted, :bool, 6
    end
    add_message "apikeyserver.KeyResponseRemaining" do
      optional :KeyResponseTypeNames, :string, 1
      optional :typeRemaining, :uint32, 2
    end
    add_message "apikeyserver.KeyResponseTypeNames" do
      optional :typeName, :string, 1
    end
    add_message "apikeyserver.RequestKillKey" do
      optional :requester, :string, 1
      optional :key, :string, 2
      optional :name, :string, 3
      optional :time, :int64, 4
    end
    add_message "apikeyserver.RequestPermKillKey" do
      optional :requester, :string, 1
      optional :key, :string, 2
      optional :name, :string, 3
      optional :time, :int64, 4
    end
    add_message "apikeyserver.GenericKillResponse" do
      optional :result, :bool, 1
      optional :time, :int64, 2
    end
    add_message "apikeyserver.GetServerInfoResponse" do
      optional :serverVersion, :string, 1
      optional :keyExhaustions, :uint32, 2
      optional :totalAvailableUsesPerMin, :uint64, 3
      optional :totalKeysServed, :uint64, 4
      optional :totalKeysKilled, :uint64, 5
      optional :keyNamesPermaKilled, :string, 6
      repeated :items, :message, 7, "apikeyserver.KeyDetailsResponse"
      optional :time, :int64, 8
      optional :uptime, :int64, 9
      optional :avgKeysServedPerMin, :float, 10
    end
    add_message "apikeyserver.KeyDetailsResponse" do
      optional :name, :string, 1
      optional :types, :string, 2
      optional :uses, :uint32, 3
      optional :kills, :uint32, 4
      optional :active, :bool, 5
    end
  end
end

module Apikeyserver
  RequestKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.RequestKey").msgclass
  RequestServerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.RequestServerInfo").msgclass
  GetKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.GetKeyResponse").msgclass
  KeyResponseRemaining = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.KeyResponseRemaining").msgclass
  KeyResponseTypeNames = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.KeyResponseTypeNames").msgclass
  RequestKillKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.RequestKillKey").msgclass
  RequestPermKillKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.RequestPermKillKey").msgclass
  GenericKillResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.GenericKillResponse").msgclass
  GetServerInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.GetServerInfoResponse").msgclass
  KeyDetailsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("apikeyserver.KeyDetailsResponse").msgclass
end
