// source: apiKeyServer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.apikeyserver.TimedKillResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.apikeyserver.GenericKillResponse');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apikeyserver.TimedKillResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apikeyserver.TimedKillResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apikeyserver.TimedKillResponse.displayName = 'proto.apikeyserver.TimedKillResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apikeyserver.TimedKillResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.apikeyserver.TimedKillResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apikeyserver.TimedKillResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apikeyserver.TimedKillResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    result: (f = msg.getResult()) && proto.apikeyserver.GenericKillResponse.toObject(includeInstance, f),
    returntoservice: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apikeyserver.TimedKillResponse}
 */
proto.apikeyserver.TimedKillResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apikeyserver.TimedKillResponse;
  return proto.apikeyserver.TimedKillResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apikeyserver.TimedKillResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apikeyserver.TimedKillResponse}
 */
proto.apikeyserver.TimedKillResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.apikeyserver.GenericKillResponse;
      reader.readMessage(value,proto.apikeyserver.GenericKillResponse.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReturntoservice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apikeyserver.TimedKillResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apikeyserver.TimedKillResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apikeyserver.TimedKillResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apikeyserver.TimedKillResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.apikeyserver.GenericKillResponse.serializeBinaryToWriter
    );
  }
  f = message.getReturntoservice();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional GenericKillResponse result = 1;
 * @return {?proto.apikeyserver.GenericKillResponse}
 */
proto.apikeyserver.TimedKillResponse.prototype.getResult = function() {
  return /** @type{?proto.apikeyserver.GenericKillResponse} */ (
    jspb.Message.getWrapperField(this, proto.apikeyserver.GenericKillResponse, 1));
};


/**
 * @param {?proto.apikeyserver.GenericKillResponse|undefined} value
 * @return {!proto.apikeyserver.TimedKillResponse} returns this
*/
proto.apikeyserver.TimedKillResponse.prototype.setResult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apikeyserver.TimedKillResponse} returns this
 */
proto.apikeyserver.TimedKillResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apikeyserver.TimedKillResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 returnToService = 2;
 * @return {number}
 */
proto.apikeyserver.TimedKillResponse.prototype.getReturntoservice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.apikeyserver.TimedKillResponse} returns this
 */
proto.apikeyserver.TimedKillResponse.prototype.setReturntoservice = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


