// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.11.4
// source: apikeyserver/apiKeyServer.proto

package apikeyserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiKeyServerClient is the client API for ApiKeyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiKeyServerClient interface {
	GetKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Key, error)
	KillKey(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*Result, error)
	PermKillKey(ctx context.Context, in *PermKillRequest, opts ...grpc.CallOption) (*Result, error)
}

type apiKeyServerClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeyServerClient(cc grpc.ClientConnInterface) ApiKeyServerClient {
	return &apiKeyServerClient{cc}
}

func (c *apiKeyServerClient) GetKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, "/apikeyserver.ApiKeyServer/GetKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyServerClient) KillKey(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/apikeyserver.ApiKeyServer/KillKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyServerClient) PermKillKey(ctx context.Context, in *PermKillRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/apikeyserver.ApiKeyServer/PermKillKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeyServerServer is the server API for ApiKeyServer service.
// All implementations must embed UnimplementedApiKeyServerServer
// for forward compatibility
type ApiKeyServerServer interface {
	GetKey(context.Context, *Request) (*Key, error)
	KillKey(context.Context, *KillRequest) (*Result, error)
	PermKillKey(context.Context, *PermKillRequest) (*Result, error)
	mustEmbedUnimplementedApiKeyServerServer()
}

// UnimplementedApiKeyServerServer must be embedded to have forward compatible implementations.
type UnimplementedApiKeyServerServer struct {
}

func (UnimplementedApiKeyServerServer) GetKey(context.Context, *Request) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedApiKeyServerServer) KillKey(context.Context, *KillRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillKey not implemented")
}
func (UnimplementedApiKeyServerServer) PermKillKey(context.Context, *PermKillRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermKillKey not implemented")
}
func (UnimplementedApiKeyServerServer) mustEmbedUnimplementedApiKeyServerServer() {}

// UnsafeApiKeyServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeyServerServer will
// result in compilation errors.
type UnsafeApiKeyServerServer interface {
	mustEmbedUnimplementedApiKeyServerServer()
}

func RegisterApiKeyServerServer(s grpc.ServiceRegistrar, srv ApiKeyServerServer) {
	s.RegisterService(&ApiKeyServer_ServiceDesc, srv)
}

func _ApiKeyServer_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServerServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apikeyserver.ApiKeyServer/GetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServerServer).GetKey(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeyServer_KillKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServerServer).KillKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apikeyserver.ApiKeyServer/KillKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServerServer).KillKey(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeyServer_PermKillKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyServerServer).PermKillKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apikeyserver.ApiKeyServer/PermKillKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyServerServer).PermKillKey(ctx, req.(*PermKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeyServer_ServiceDesc is the grpc.ServiceDesc for ApiKeyServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeyServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apikeyserver.ApiKeyServer",
	HandlerType: (*ApiKeyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _ApiKeyServer_GetKey_Handler,
		},
		{
			MethodName: "KillKey",
			Handler:    _ApiKeyServer_KillKey_Handler,
		},
		{
			MethodName: "PermKillKey",
			Handler:    _ApiKeyServer_PermKillKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apikeyserver/apiKeyServer.proto",
}
